const ACTION_LOGIN = {type : "ACTION_LOGIN"}
const ACTION_LOGOUT = {type : "ACTION_LOGOUT"}

const ACTION_ADD_COMMENT = {type : "ACTION_ADD_COMMENT"}
const ACTION_REMOVE_COMMENT = {type : "ACTION_REMOVE_COMMENT"}



export {ACTION_LOGIN,ACTION_LOGOUT,ACTION_ADD_COMMENT,ACTION_REMOVE_COMMENT} 